print("*********************************************************************")
print("Este código pede 4 notas de um aluno e devolve a média desses valores")
print("*********************************************************************")
print()

nota_str = input("Digite a primeira nota: ")
nota_1 = float(nota_str)
print()
nota_str = input("Digite a segunda nota: ")
nota_2 = float(nota_str)
print()
nota_str = input("Digite a terceira nota: ")
nota_3 = float(nota_str)
print()
nota_str = input("Digite a última nota: ")
nota_4 = float(nota_str)
print()
media = (nota_1 + nota_2 + nota_3 + nota_4) / 4
print("A média das notas é {:.2}".format(media))
